const mongoose = require('mongoose');

const ChecklistInstanceSchema = new mongoose.Schema({
    template: { // Link to the template that was used
        type: mongoose.Schema.Types.ObjectId,
        ref: 'ChecklistTemplate',
        required: true,
    },
    targetUser: { // The user this checklist was applied to
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
        required: true,
    },
    status: {
        type: String,
        enum: ['In Progress', 'Completed'],
        default: 'In Progress',
    },
    startDate: {
        type: Date,
        required: true,
    },
    completionDate: {
        type: Date,
    },
    // The list of all real Task documents that were generated by this instance
    generatedTasks: [{
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Task'
    }],
    // Who triggered this checklist?
    createdBy: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
        required: true,
    }
}, { timestamps: true });

module.exports = mongoose.model('ChecklistInstance', ChecklistInstanceSchema);